
# This script needs to be run in project mode, assumes 
# project is already generated by fusesoc

# Top level design from environment variable 

set FPGA_PART xczu7ev-ffvc1156-2-e
set TOP_LEVEL cve2_top
set SYN_REPORT_DIR output/rpts/syn
set MAX_THREADS 12

set timestamp [clock format [clock seconds] -format {%Y%m%d_%H%M}]
set  REPORT_DIR "$SYN_REPORT_DIR/$timestamp"
set SYN_CKPT_NAME "cve2_top_synth.dcp"
set CKPTS_DIR output/ckpts

set_param general.maxThreads $MAX_THREADS

file mkdir $REPORT_DIR
file mkdir $CKPTS_DIR


proc report_fmax {rpt_file} {

    # Get WNS
    set wns [get_property SLACK [get_timing_paths -delay_type max -max_paths 1]]

    # Get clock freq
    set clk_period_ns [get_property PERIOD [get_clocks clk_i]]

    set fmax [expr 1.0 / ($clk_period_ns - $wns) * 1000.0]  

    set fmax_rpt_file "$rpt_file"
    set fmax_fd [open $fmax_rpt_file "w"]
    puts $fmax_fd "WNS: $wns ns"
    puts $fmax_fd "Maximum Frequency (FMAX): $fmax MHz"
    close $fmax_fd
}

puts "Running Vivado synthesis for CVE2"
synth_design -top $TOP_LEVEL -part $FPGA_PART -flatten_hierarchy rebuilt \
    -max_dsp 0  

# Report utilization for top level
puts "Writing top level utilization report to $REPORT_DIR/cve2_top_util.rpt"
report_utilization -file $REPORT_DIR/cve2_top_util.rpt -hierarchical

puts "Writing cf_unit utilization report to $REPORT_DIR/cf_unit.rpt"
report_utilization -file $REPORT_DIR/cf_unit.rpt \
    -cells [get_cells -hierarchical -filter {NAME =~ "*cf_unit_i*"}]

# Report timing
puts "Writing timing summary to $REPORT_DIR/timing_summary.rpt"
report_timing_summary -delay_type min_max -report_unconstrained \
            -check_timing_verbose -max_paths 10 \
            -input_pins -routable_nets \
            -file $REPORT_DIR/timing_summary.rpt

puts "Writing timing max paths report to $REPORT_DIR/cve2_top_timing_max_paths.rpt"
report_timing -max_paths 10 -file $REPORT_DIR/cve2_top_timing_max_paths.rpt

puts "Writing timing max paths report to $REPORT_DIR/cve2_top_timing_max_paths.rpt"
report_fmax $REPORT_DIR/cve2_top_fmax.rpt

puts "Synthesis complete. Check $REPORT_DIR for reports"

# Checkpoint design for platform integration
write_checkpoint -force -file $CKPTS_DIR/$SYN_CKPT_NAME

puts "Design checkpoint saved to $CKPTS_DIR/$SYN_CKPT_NAME"
