
# This script needs to be run in project mode, assumes 
# project is already generated by fusesoc

# Top level design from environment variable 

source [file join [file dirname [info script]] util.tcl]

set FPGA_PART xczu7ev-ffvc1156-2-e
set SYN_REPORT_DIR output/rpts/mac_impl
set MAX_THREADS 32

set timestamp [clock format [clock seconds] -format {%Y%m%d_%H%M}]
set  REPORT_DIR "$SYN_REPORT_DIR/$timestamp"
set SYN_CKPT_NAME "cve2_mac_synth.dcp"
set CKPTS_DIR output/ckpts

set_param general.maxThreads $MAX_THREADS

file mkdir $REPORT_DIR
file mkdir $CKPTS_DIR


puts "Running Vivado synthesis for CVE2"

set_property -name {STEPS.SYNTH_DESIGN.ARGS.MORE OPTIONS} -value {-mode out_of_context} -object [get_runs synth_1]
set_property top cve2_cf_mac_unit [current_fileset]

reset_runs impl_1
launch_runs impl_1 -jobs $MAX_THREADS
wait_on_run impl_1

open_run impl_1

# synth_design -mode out_of_context -top $TOP_LEVEL -part $FPGA_PART -flatten_hierarchy rebuilt -max_dsp 0  

# Report utilization for top level
report_utilization -file $REPORT_DIR/cve2_top_util.rpt -hierarchical


# Report timing
puts "Writing timing summary to $REPORT_DIR/timing_summary.rpt"
report_timing_summary -delay_type min_max -report_unconstrained \
            -check_timing_verbose -max_paths 10 \
            -input_pins -routable_nets \
            -file $REPORT_DIR/timing_summary.rpt

puts "Writing timing max paths report to $REPORT_DIR/cve2_top_timing_max_paths.rpt"
report_timing -max_paths 10 -file $REPORT_DIR/cve2_top_timing_max_paths.rpt

puts "Writing timing max paths report to $REPORT_DIR/cve2_top_timing_max_paths.rpt"
report_fmax $REPORT_DIR/cve2_top_fmax.rpt clk_i

puts "Synthesis complete. Check $REPORT_DIR for reports"

# Checkpoint design for platform integration
write_checkpoint -force -file $CKPTS_DIR/$SYN_CKPT_NAME

puts "Design checkpoint saved to $CKPTS_DIR/$SYN_CKPT_NAME"
