
# This script needs to be run in project mode, assumes
# project is already generated by fusesoc

# Top level design from environment variable

source [file join [file dirname [info script]] util.tcl]

set FPGA_PART xczu7ev-ffvc1156-2-e
set TOP_LEVEL cve2_top
set IMPL_REPORT_DIR output/rpts/impl
set OUTPUT_DIR output
set MAX_THREADS 12

# Verilog files for support IP
set SUPPORT_IP_DIR [file normalize "../support_ip"]

set timestamp [clock format [clock seconds] -format {%Y%m%d_%H%M}]
set REPORT_DIR "$IMPL_REPORT_DIR/$timestamp"

set_param general.maxThreads $MAX_THREADS

file mkdir $REPORT_DIR
file mkdir $OUTPUT_DIR

# Build the processing system block design
source "$SUPPORT_IP_DIR/ps.tcl"

# Add the support IP sources
add_files \
    "$SUPPORT_IP_DIR/accelerator_top.sv" \
    "$SUPPORT_IP_DIR/memory_system.sv" \
    "$SUPPORT_IP_DIR/program.mem"

# Set the platform top level
set_property top accelerator_top [current_fileset]
update_compile_order -fileset [current_fileset]

synth_design -top $TOP_LEVEL -part $FPGA_PART -flatten_hierarchy rebuilt \
    -max_dsp 0  

# Generate the bitstream (runs synthesis + implementation + write_bitstream)
puts "Launching implementation run to generate bitstream"
launch_runs impl_1 -to_step write_bitstream -jobs $MAX_THREADS
wait_on_run impl_1

# Open the implemented design for reporting and export
open_run impl_1

# Report utilization for top level
puts "Writing top level utilization report to $REPORT_DIR/cve2_top_util.rpt"
report_utilization -file $REPORT_DIR/cve2_top_util.rpt -hierarchical

puts "Writing cf_unit utilization report to $REPORT_DIR/cf_unit.rpt"
report_utilization -file $REPORT_DIR/cf_unit.rpt \
    -cells [get_cells -hierarchical -filter {NAME =~ "*cf_unit_i*"}]

# Report timing
puts "Writing timing summary to $REPORT_DIR/timing_summary.rpt"
report_timing_summary -delay_type min_max -report_unconstrained \
            -check_timing_verbose -max_paths 10 \
            -input_pins -routable_nets \
            -file $REPORT_DIR/timing_summary.rpt

puts "Writing timing max paths report to $REPORT_DIR/cve2_top_timing_max_paths.rpt"
report_timing -max_paths 10 -file $REPORT_DIR/cve2_top_timing_max_paths.rpt

# The platform PL clock is derived from the PS pl_clk0 output (auto-named clk_pl_0)
puts "Writing fmax report to $REPORT_DIR/cve2_top_fmax.rpt"
report_fmax $REPORT_DIR/cve2_top_fmax.rpt clk_pl_0

puts "Implementation complete. Check $REPORT_DIR for reports"

# Save the generated bitstream to the output directory
set bit_file [file join $OUTPUT_DIR accelerator_top.bit]
write_bitstream -force $bit_file
puts "Bitstream written to $bit_file"

# Export hardware handoff for Vitis (Export -> Export Hardware, include bitstream)
set xsa_file [file join $OUTPUT_DIR accelerator_top.xsa]
write_hw_platform -fixed -include_bit -force $xsa_file
puts "Hardware platform exported to $xsa_file"
